/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JFrame;


/**
 *
 * @author alunos
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);  //Centraliza a tela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemIncluir = new javax.swing.JMenuItem();
        jMenuItemAlterar = new javax.swing.JMenuItem();
        jMenuItemExcluir = new javax.swing.JMenuItem();
        jMenuItemRelatorio = new javax.swing.JMenuItem();
        jMenuItem_aumenta_salario = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Gerenciador de Recursos Humanos");
        setBackground(java.awt.Color.white);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/java-logo.png"))); // NOI18N

        jMenuCadastro.setText("Cadastro");

        jMenuItemIncluir.setText("Incluir");
        jMenuItemIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIncluirActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemIncluir);

        jMenuItemAlterar.setText("Alterar");
        jMenuItemAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemAlterar);

        jMenuItemExcluir.setText("Excluir");
        jMenuItemExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExcluirActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemExcluir);

        jMenuItemRelatorio.setText("Relatorio");
        jMenuItemRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemRelatorio);

        jMenuItem_aumenta_salario.setText("Dar Aumento");
        jMenuItem_aumenta_salario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_aumenta_salarioActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItem_aumenta_salario);

        jMenuBar1.add(jMenuCadastro);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Encerrar");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIncluirActionPerformed
        Incluir telaIncluir = new Incluir();
        telaIncluir.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        telaIncluir.setVisible(true);

    }//GEN-LAST:event_jMenuItemIncluirActionPerformed

    private void jMenuItemAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarActionPerformed
        // TODO add your handling code here:
        Alterar telaAlterar = new Alterar();
        telaAlterar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        telaAlterar.setVisible(true);
    }//GEN-LAST:event_jMenuItemAlterarActionPerformed

    private void jMenuItemExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExcluirActionPerformed
        // TODO add your handling code here:
        Excluir telaExcluir = new Excluir();
        telaExcluir.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        telaExcluir.setVisible(true);
    }//GEN-LAST:event_jMenuItemExcluirActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioActionPerformed
        // TODO add your handling code here:
        Relatorio telaRelatorio = new Relatorio();
        telaRelatorio.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        telaRelatorio.setVisible(true);
    }//GEN-LAST:event_jMenuItemRelatorioActionPerformed

    private void jMenuItem_aumenta_salarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_aumenta_salarioActionPerformed
        AumentarSalario telaAumento = new AumentarSalario();
        telaAumento.setVisible(true);
    }//GEN-LAST:event_jMenuItem_aumenta_salarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItemAlterar;
    private javax.swing.JMenuItem jMenuItemExcluir;
    private javax.swing.JMenuItem jMenuItemIncluir;
    private javax.swing.JMenuItem jMenuItemRelatorio;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItem_aumenta_salario;
    private javax.swing.JMenu jMenuSair;
    // End of variables declaration//GEN-END:variables
}
